### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by nsleche** [arn00s/barceloneta#1]
it'd be cool to have a swift 3 version, if you have any interest to create a branch i would like to help with that.

**Comment by zigzagg16** [comment]
Hi @nschucky , I did a very basic conversion to Swift 3, check the swift_3 branch and don't hesitate if you wanna improve ! Thanks !

**Comment by zigzagg16** [comment]
Hi @nschucky , I guess you saw it, it's Swift 3 compatible
